[package]
name = "nexus-chat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[[bin]]
name = "nexus"
path = "src/main.rs"

[dependencies]
nexus-chat-core = { path = "../core" }
anyhow = { workspace = true }
arboard = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
futures-util = { workspace = true }
image = { workspace = true }
open = { workspace = true }
ratatui = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
textwrap = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tui-textarea-2 = { workspace = true }
uuid = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
nexus-chat-core = { path = "../core", features = ["test-helpers"] }
